platform :ios, '8.0'

target 'ExampleSSDataSources' do
  pod 'SSDataSources', :path => '../'

  target 'ExampleSSDataSourcesTests' do
    inherit! :search_paths

  pod 'Expecta'
  pod 'OCMock'
  pod 'MagicalRecord'
  end
end

