platform :ios, '6.0'

xcodeproj 'ExampleSSDataSources'

pod 'SSDataSources', :path => "../"

target :ExampleSSDataSourcesTests, :exclusive => true do
  # A Matcher Framework for Objective-C/Cocoa with nicer assertions
  # than OCUnit's (though it still works within SenTestCase subclasses).
  pod 'Expecta', '~> 0.2.1'

  # For mocking/faking objects, primarily UITableView/UICollectionView
  pod 'OCMock', '~> 2.2'
end
