#!/bin/sh

set -e

cd Example
pod install
xctool -workspace ExampleSSDataSources.xcworkspace -scheme ExampleSSDataSources -sdk iphonesimulator build test ONLY_ACTIVE_ARCH=NO RUN_CLANG_STATIC_ANALYZER=YES CLANG_STATIC_ANALYZER_MODE=deep
