#!/bin/bash

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

set -o pipefail && xcodebuild \
-workspace Example/ExampleSSDataSources.xcworkspace \
-scheme ExampleSSDataSources \
-sdk iphonesimulator \
-destination "platform=iOS Simulator,name=iPhone 6" \
clean test \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep | xcpretty -c
