#!/bin/sh

set -e

xcodebuild \
-workspace Example/ExampleSSDataSources.xcworkspace \
-scheme ExampleSSDataSources \
-sdk iphonesimulator \
clean build test \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep | xcpretty -c
